// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: programme.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProgrammeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgrammeRequest) Reset() {
	*x = GetProgrammeRequest{}
	mi := &file_programme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgrammeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgrammeRequest) ProtoMessage() {}

func (x *GetProgrammeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_programme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgrammeRequest.ProtoReflect.Descriptor instead.
func (*GetProgrammeRequest) Descriptor() ([]byte, []int) {
	return file_programme_proto_rawDescGZIP(), []int{0}
}

func (x *GetProgrammeRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type Programme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Live          bool                   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Images        *Image                 `protobuf:"bytes,5,opt,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Programme) Reset() {
	*x = Programme{}
	mi := &file_programme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Programme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Programme) ProtoMessage() {}

func (x *Programme) ProtoReflect() protoreflect.Message {
	mi := &file_programme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Programme.ProtoReflect.Descriptor instead.
func (*Programme) Descriptor() ([]byte, []int) {
	return file_programme_proto_rawDescGZIP(), []int{1}
}

func (x *Programme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Programme) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *Programme) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Programme) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Programme) GetImages() *Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Standard      string                 `protobuf:"bytes,2,opt,name=standard,proto3" json:"standard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_programme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_programme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_programme_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Image) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

var File_programme_proto protoreflect.FileDescriptor

const file_programme_proto_rawDesc = "" +
	"\n" +
	"\x0fprogramme.proto\x12\tprogramme\"'\n" +
	"\x13GetProgrammeRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"\x83\x01\n" +
	"\tProgramme\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04live\x18\x02 \x01(\bR\x04live\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12(\n" +
	"\x06images\x18\x05 \x01(\v2\x10.programme.ImageR\x06images\"7\n" +
	"\x05Image\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bstandard\x18\x02 \x01(\tR\bstandard2Z\n" +
	"\x10ProgrammeService\x12F\n" +
	"\fGetProgramme\x12\x1e.programme.GetProgrammeRequest\x1a\x14.programme.Programme\"\x00B-Z+github.com/iuketaylor/grpc_programmes/protob\x06proto3"

var (
	file_programme_proto_rawDescOnce sync.Once
	file_programme_proto_rawDescData []byte
)

func file_programme_proto_rawDescGZIP() []byte {
	file_programme_proto_rawDescOnce.Do(func() {
		file_programme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_programme_proto_rawDesc), len(file_programme_proto_rawDesc)))
	})
	return file_programme_proto_rawDescData
}

var file_programme_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_programme_proto_goTypes = []any{
	(*GetProgrammeRequest)(nil), // 0: programme.GetProgrammeRequest
	(*Programme)(nil),           // 1: programme.Programme
	(*Image)(nil),               // 2: programme.Image
}
var file_programme_proto_depIdxs = []int32{
	2, // 0: programme.Programme.images:type_name -> programme.Image
	0, // 1: programme.ProgrammeService.GetProgramme:input_type -> programme.GetProgrammeRequest
	1, // 2: programme.ProgrammeService.GetProgramme:output_type -> programme.Programme
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_programme_proto_init() }
func file_programme_proto_init() {
	if File_programme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_programme_proto_rawDesc), len(file_programme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_programme_proto_goTypes,
		DependencyIndexes: file_programme_proto_depIdxs,
		MessageInfos:      file_programme_proto_msgTypes,
	}.Build()
	File_programme_proto = out.File
	file_programme_proto_goTypes = nil
	file_programme_proto_depIdxs = nil
}
