// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: programme.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgrammeService_GetProgramme_FullMethodName = "/programme.ProgrammeService/GetProgramme"
)

// ProgrammeServiceClient is the client API for ProgrammeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgrammeServiceClient interface {
	GetProgramme(ctx context.Context, in *GetProgrammeRequest, opts ...grpc.CallOption) (*Programme, error)
}

type programmeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgrammeServiceClient(cc grpc.ClientConnInterface) ProgrammeServiceClient {
	return &programmeServiceClient{cc}
}

func (c *programmeServiceClient) GetProgramme(ctx context.Context, in *GetProgrammeRequest, opts ...grpc.CallOption) (*Programme, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Programme)
	err := c.cc.Invoke(ctx, ProgrammeService_GetProgramme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgrammeServiceServer is the server API for ProgrammeService service.
// All implementations must embed UnimplementedProgrammeServiceServer
// for forward compatibility.
type ProgrammeServiceServer interface {
	GetProgramme(context.Context, *GetProgrammeRequest) (*Programme, error)
	mustEmbedUnimplementedProgrammeServiceServer()
}

// UnimplementedProgrammeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgrammeServiceServer struct{}

func (UnimplementedProgrammeServiceServer) GetProgramme(context.Context, *GetProgrammeRequest) (*Programme, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgramme not implemented")
}
func (UnimplementedProgrammeServiceServer) mustEmbedUnimplementedProgrammeServiceServer() {}
func (UnimplementedProgrammeServiceServer) testEmbeddedByValue()                          {}

// UnsafeProgrammeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgrammeServiceServer will
// result in compilation errors.
type UnsafeProgrammeServiceServer interface {
	mustEmbedUnimplementedProgrammeServiceServer()
}

func RegisterProgrammeServiceServer(s grpc.ServiceRegistrar, srv ProgrammeServiceServer) {
	// If the following call pancis, it indicates UnimplementedProgrammeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgrammeService_ServiceDesc, srv)
}

func _ProgrammeService_GetProgramme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgrammeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammeServiceServer).GetProgramme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammeService_GetProgramme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammeServiceServer).GetProgramme(ctx, req.(*GetProgrammeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgrammeService_ServiceDesc is the grpc.ServiceDesc for ProgrammeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgrammeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "programme.ProgrammeService",
	HandlerType: (*ProgrammeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProgramme",
			Handler:    _ProgrammeService_GetProgramme_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "programme.proto",
}
